### ISSUE TITLE
A new take on reducing travis test time for perl6/doc

### ISSUE THREAD

**Issue by nxadm** [perl6/doc#1946]
On issue #1765 some options were implemented:
- whateverable
- docker

I propose a new take that, in my view, is easier to maintain and probably faster: a deb package containing rakudo, zef and **all the perl6 modules** specified in the [META6.json of this repo](https://github.com/perl6/doc/blob/master/META6.json).

To use this package, this need to be added to a .travis.yml file:
```yaml
env:
  global:
    - PATH="/opt/rakudo-pkg-for-doc/bin:/opt/rakudo-pkg-for-doc/share/perl6/site/bin:$PATH"
sudo: required
install:
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 379CE192D401AB61
  - echo "deb https://dl.bintray.com/nxadm/perl6-doc trusty main" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update && sudo apt-get install rakudo-pkg-for-doc
``` 
There is no need to specify a version, you'll always get the latest released Rakudo.

If this solution proofs itself useful, a new package will be created and automatically uploaded to the repo by travis for every Rakudo release. 

The automation of the pkg creation and repo upload are handled in this repo:
https://github.com/nxadm/rakudo-pkg-for-doc

cc: @JJ

**Comment by coke** [comment]
Thought: this will break if we ever change the required modules list.

**Comment by nxadm** [comment]
It depends. The pkg takes the modules list directly from the repo, so a new package needs to be respinned. Just chaning the revision to "02" will trigger the build for a new package that will obsolete the previous one. It can be probably automated if changing dependencies is something that happens often.

**Comment by JJ** [comment]
The current test includes a docker container that already packs all required modules, and will break as soon as we change it. The whateverable binary, on the other hands, installs them and it takes some time. I'll put this one for testing in the shippable version (in #1931) first.

**Comment by JJ** [comment]
And thanks a lot, @nxadm , for preparing this.

**Comment by AlexDaniel** [comment]
> * the dynamism of adding module dependencies on the fly.
> * or shave some minutes (I didn't time it, but building the deps takes a long time) for every commit.

Why can't we have both? Surely it can install modules that are not installed on the fly?

**Comment by nxadm** [comment]
@AlexDaniel 
LOL, yes. I hadnt't though that zef is supplied in the package and can install modules :)

**Comment by JJ** [comment]
2018-04-21 10:58 GMT+02:00 Aleks-Daniel Jakimenko-Aleksejev <
notifications@github.com>:

>
>    - the dynamism of adding module dependencies on the fly.
>    - or shave some minutes (I didn't time it, but building the deps takes
>    a long time) for every commit.
>
> Why can't we have both? Surely it can install modules that are not
> installed on the fly?
>
Theoretically, we should have achieved that using shippable's cache. I
couldn't make it work, however.
Anyway, the Whateverable version does add modules on the fly, so we can
have the cake and eat it too with the matrix.

**Comment by JJ** [comment]
Installing modules takes around 4 minutes, however. If we really want to
make it faster, that's our next frontier.
We still have the fallback option, and we can also have rakudobrew built
for us. But having a fast response, for PRs for instance, makes all the
difference.

**Comment by nxadm** [comment]
Instruction could be amended to:
```yaml
env:
  global:
    - PATH="/opt/rakudo-pkg-for-doc/bin:/opt/rakudo-pkg-for-doc/share/perl6/site/bin:$PATH"
sudo: required
install:
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 379CE192D401AB61
  - echo "deb https://dl.bintray.com/nxadm/perl6-doc trusty main" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update && sudo apt-get install rakudo-pkg-for-doc
  - sudo zef --deps-only install .
```
