### ISSUE TITLE
[feature request] add just a bit of styling to pre blocks (html output)

### ISSUE THREAD

**Issue by uvtc** [perl6/doc#8]
In the html output at doc.perl6.org, it would be nice if the <pre> blocks stood out a little bit from the surrounding text. Consider adding this to the css:

``` css
pre {
    background-color: #f4f4f8;
    border: 1px solid #ededf2;
    padding: 6px;
}
```
